version: '3'
services:

  host-mongodb:
    container_name: host-mongodb
    image: mongo:3.6
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  app:
    build:
      context: app
      dockerfile: Dockerfile
    working_dir: /src/main/java
    volumes:
      - ./src/main/java:/src/main/java
      - ~/.m2:/root/.m2
    expose:
      - 8080
    command: mvn clean install spring-boot:run
    depends_on:
      - host-mongodb